import express from 'express';
import * as examController from '../controllers/examController.js';
import * as questionController from '../controllers/questionController.js';
import { authenticate, requireExaminer, requireClient } from '../middleware/authMiddleware.js';
const router=express.Router();
router.get('/exams', authenticate, examController.listExams);
router.get('/exams/:examId', authenticate, examController.getExam);
router.post('/exams', authenticate, requireExaminer, examController.createExam);
router.put('/exams/:examId', authenticate, requireExaminer, examController.updateExam);
router.delete('/exams/:examId', authenticate, requireExaminer, examController.deleteExam);
router.post('/exams/:examId/questions', authenticate, requireExaminer, questionController.createQuestion);
router.put('/questions/:questionId', authenticate, requireExaminer, questionController.updateQuestion);
router.delete('/questions/:questionId', authenticate, requireExaminer, questionController.deleteQuestion);
export default router;
